# Generated by Django 4.1.3 on 2022-11-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(default='default.png', upload_to=pathlib.PureWindowsPath('C:/priv/python/imageProject/media'))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Plan name'),
        ),
        migrations.CreateModel(
            name='ImageThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='imageapi.image')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imageapi.planthumbnail')),
            ],
        ),
    ]
