# Generated by Django 4.1.3 on 2022-11-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imageapi.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageapi', '0002_image_alter_serviceplan_name_imagethumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='temp_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='temp_link_expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=imageapi.models.random_path, validators=[imageapi.models.png_or_jpg]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
