# Generated by Django 4.1.3 on 2022-11-21 18:45

from django.db import migrations, models
import imageapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0003_image_temp_link_image_temp_link_expire_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='temp_link_longevity',
            field=models.IntegerField(blank=True, null=True, validators=[imageapi.models.longevity_validator]),
        ),
    ]
