# Generated by Django 4.1.3 on 2022-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0004_image_temp_link_longevity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='temp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
