# Generated by Django 4.1.3 on 2022-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0005_alter_image_temp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='temp_id',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='temp_link',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
