# Generated by Django 4.1.3 on 2022-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0006_image_temp_id_alter_image_temp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='temp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
